// News Loader for GeoDI Lab - Reads from GitHub Actions generated JSON
class NewsLoader {
    constructor() {
        this.newsContainer = document.querySelector('.news-list');
        this.loadingElement = document.querySelector('.loading-news');
        this.errorElement = document.querySelector('.news-error');
        this.maxNewsItems = 3;
        this.newsDataUrl = 'data/latest-news.json';
    }

    async loadNews() {
        try {
            // Show loading state
            this.showLoading();
            
            // Fetch news from JSON file (generated by GitHub Actions)
            const newsItems = await this.fetchNewsFromJSON();
            
            // Display the news
            this.displayNews(newsItems);
            
        } catch (error) {
            console.error('Error loading news:', error);
            // Fallback to static data if JSON fetch fails
            const fallbackNews = this.getFallbackNews();
            this.displayNews(fallbackNews);
        }
    }

    async fetchNewsFromJSON() {
        try {
            console.log('Fetching news from JSON file:', this.newsDataUrl);
            
            const response = await fetch(this.newsDataUrl);
            
            if (!response.ok) {
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            
            const data = await response.json();
            console.log('JSON data received:', data);
            
            if (!data.items || data.items.length === 0) {
                throw new Error('No items found in JSON data');
            }
            
            console.log('=== JSON FETCH SUCCESSFUL ===');
            console.log('Total items from JSON:', data.items.length);
            console.log('Last updated:', data.last_updated);
            console.log('All titles:', data.items.map(item => item.title));
            
            // Convert JSON format to our format
            const newsItems = data.items.map((item, index) => {
                console.log(`Processing JSON item ${index + 1}:`, item);
                
                const title = item.title || '';
                const description = item.description || '';
                const url = item.url || '';
                const pubDate = item.date || '';
                
                // Format the date
                const formattedDate = this.formatDate(pubDate);
                
                console.log(`Processed JSON item ${index + 1}: "${title}"`);
                
                return {
                    title: title,
                    description: description,
                    date: formattedDate,
                    url: url
                };
            });
            
            console.log(`Converted ${newsItems.length} items from JSON`);
            
            // Return top 3 items
            const topNews = newsItems.slice(0, this.maxNewsItems);
            console.log(`Returning top ${topNews.length} news items:`, topNews.map(item => item.title));
            
            return topNews;
            
        } catch (error) {
            console.error('=== JSON FETCH FAILED ===');
            console.error('Error:', error.message);
            throw error; // Let the main loadNews function handle fallback
        }
    }

    formatDate(dateString) {
        try {
            const date = new Date(dateString);
            const now = new Date();
            const diffTime = Math.abs(now - date);
            const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
            
            if (diffDays === 1) {
                return 'Today';
            } else if (diffDays === 2) {
                return 'Yesterday';
            } else if (diffDays <= 7) {
                return `${diffDays - 1} days ago`;
            } else {
                return date.toLocaleDateString('en-US', { 
                    month: 'short', 
                    day: 'numeric',
                    year: date.getFullYear() !== now.getFullYear() ? 'numeric' : undefined
                });
            }
        } catch (error) {
            return 'Recent';
        }
    }

    getFallbackNews() {
        console.log('Using fallback news data (3 items)');
        
        // Fallback data if JSON fetch fails
        const newsData = [
            {
                title: "Deep panel flow inference paper published on IJGIS",
                description: "GeoDI lab's recent research article, introducing a gravity-informed Deep Spatial Evolution Network (DSEN) to infer panel spatial flows, has been published in the International Journal of Geographical Information Science.",
                date: "Recent",
                url: "https://geodi.umn.edu/deep-panel-flow-inference-paper-published-ijgis"
            },
            {
                title: "The Weather-Informed Mobility Network (WIMN) paper is published on IJGIS",
                description: "Latest research on Weather-Informed Mobility Network (WIMN) has been published in the International Journal of Geographical Information Science, showcasing innovative approaches to understanding mobility patterns in relation to weather conditions.",
                date: "Recent",
                url: "https://geodi.umn.edu/weather-informed-mobility-network-wimn-paper-published-ijgis"
            },
            {
                title: "The new 'visitor-census' article is published on Scientific Data",
                description: "New research article on visitor-census methodology has been published in Scientific Data, presenting innovative approaches to census data collection and analysis.",
                date: "Recent",
                url: "https://geodi.umn.edu/new-visitor-census-article-published-scientific-data"
            }
        ];

        console.log(`Fallback news: returning ${newsData.length} items`);
        return newsData;
    }

    displayNews(newsItems) {
        if (!this.newsContainer) {
            console.error('News container not found!');
            return;
        }

        console.log(`=== DISPLAYING NEWS ===`);
        console.log(`Displaying ${newsItems.length} news items`);

        // Clear existing content
        this.newsContainer.innerHTML = '';

        // Create news items
        newsItems.forEach((news, index) => {
            console.log(`Creating news element ${index + 1}: "${news.title}"`);
            const newsElement = this.createNewsElement(news);
            this.newsContainer.appendChild(newsElement);
        });

        console.log(`Successfully displayed ${newsItems.length} news items`);
        console.log(`=== DISPLAY COMPLETE ===`);

        // Hide loading
        this.hideLoading();
    }

    createNewsElement(news) {
        const newsItem = document.createElement('div');
        newsItem.className = 'news-item';
        
        // Clean and truncate the description for display
        const cleanDescription = this.cleanHtmlTags(news.description);
        
        // Add indicator for data source
        const dataIndicator = '<small style="color: #28a745; font-style: italic;">(Auto-updated from GeoDI RSS)</small>';
        
        newsItem.innerHTML = `
            <div class="news-date">${news.date}</div>
            <div class="news-content">
                <h4>${news.title}</h4>
                <p>${cleanDescription}</p>
                ${dataIndicator}
            </div>
        `;

        // Add click handler to open the news URL
        newsItem.style.cursor = 'pointer';
        newsItem.addEventListener('click', () => {
            window.open(news.url, '_blank');
        });

        return newsItem;
    }

    cleanHtmlTags(htmlString) {
        // Remove HTML tags and decode HTML entities
        const tempDiv = document.createElement('div');
        tempDiv.innerHTML = htmlString;
        
        // Get text content and clean it up
        let text = tempDiv.textContent || tempDiv.innerText || '';
        
        // Decode HTML entities
        text = this.decodeHtmlEntities(text);
        
        // Remove extra whitespace and newlines
        text = text.replace(/\s+/g, ' ').trim();
        
        // Limit length for display
        if (text.length > 120) {
            text = text.substring(0, 120) + '...';
        }
        
        return text;
    }

    decodeHtmlEntities(text) {
        const textarea = document.createElement('textarea');
        textarea.innerHTML = text;
        return textarea.value;
    }

    showLoading() {
        if (this.loadingElement) {
            this.loadingElement.style.display = 'block';
        }
        if (this.newsContainer) {
            this.newsContainer.style.display = 'none';
        }
    }

    hideLoading() {
        if (this.loadingElement) {
            this.loadingElement.style.display = 'none';
        }
        if (this.newsContainer) {
            this.newsContainer.style.display = 'grid';
        }
    }

    showError() {
        this.hideLoading();
        if (this.errorElement) {
            this.errorElement.style.display = 'block';
        }
    }
}

// Initialize news loader when DOM is ready
document.addEventListener('DOMContentLoaded', () => {
    const newsLoader = new NewsLoader();
    newsLoader.loadNews();
}); 